Algoritmo "Ex. 4 - Velocidade objeto."

Var

VI, A, T, V : REAL
Inicio
      ESCREVA("Digite a velocidade inicial do objeto(m/s): ")
      LEIA(VI)
      ESCREVA("Digite a aceleração do objeto(m/s^2): ")
      LEIA(A)
      ESCREVA("Digite o tempo que esse objeto está em movimento(s): ")
      LEIA(T)
      V <- VI+(A*T)
      ESCREVA("A velocidade do objeto depois de ", T, " segundos é de : ", V, " m/s")

Fimalgoritmo