a = input('Digite algo: ')
print('Qual é o tipo primitivo do valor {}?'.format(a), type(a))
print('O valor {} só tem espaços?'.format(a), a.isspace())
print('O valor {} é um número?'.format(a), a.isnumeric())
print('O valor {} é alfanumérico?'.format(a), a.isalnum())
print('O valor {} é alfabético?'.format(a), a.isalpha())
print('O valor {} está em maiúsculas?'.format(a), a.isupper())
print('O valor {} está em minúsculas?'.format(a), a.islower())
print('O valor {} está capitalizado?'.format(a), a.istitle())

